global.ownerName = "—kyynXz";
global.ownerNumber = "6281239075413";
global.botName = "`𝙎𝙞𝙢𝙥𝙡𝙚 𝙗𝙖𝙨𝙚 𝙗𝙤𝙩 𝙬𝙖`";
global.botVersion = "1.0";
global.footer = "`© 𝙋𝙤𝙬𝙚𝙧𝙚𝙙 𝙗𝙮 —𝙆𝙮𝙮𝙣𝙓𝙯`";
global.thumbnail = "https://raw.githubusercontent.com/bagus-api/storage/master/HREyJ.jpg";
global.website = "https://api.lexcode.biz.id";
global.prefix = ".";
global.idchannel = "120363424411396051@newsletter"; // Ganti jadi id channel kalian
